feat/OT151-23: add endpoint auth/login
alkemyTech/OT151-SERVER pull request #16
Opened 2022-02-24 14:46 UTC by chocolatito

### Resumen

---
Los archivos de la rama `main` modificados en este branch
- **app/controllers/api/v1/users_controller.rb**:  
  + Por migración *db/migrate/20220223015406_remove_password_from_users.rb* se necesita modificar el metodo `users_params` ya que no existe la columna `:password` en la tabla `Users`
  + Por migración *db/migrate/20220222050545_add_role_to_users.rb* se necesita agregar la asignación para el campo `role_id` del modelo `User` y un método para buscar o crear, en caso de que no exista, el rol por defecto.

- **config/routes.rb**: Añade el Endpoint _auth/login_ al espacio de nombres.

---
Nuevos archivos
- **app/controllers/api/v1/auth_controller.rb**: Agrega la acción `create` para autenticar al usuario registrado.
  + Si el valor de `email` y `password` son correctos, se retorna `email` `first_name` `last_name` `role_id` del correspondiente usuario.
  + Si el valor de `email` no correcto, se retorna `{ error: 'No such user' }` con status `unauthorized`.
  + Si el valor de `email` no correcto, pero el valor de `password` no, se retorna `{ ok: false }`.

### Comentatio/s:
Seria recomendable añadir una restricción de unicidad para la columna `name` correspondiente a la tabla `Roles`.

2022-02-24 23:04 UTC, FernandoCiballero commented on app/controllers/api/v1/auth_controller.rb
> +
Podrias limpiar un poco el controller creando un concern [Exception handler](https://github.com/loopstudio/rails-api-boilerplate/blob/master/app/controllers/concerns/exception_handler.rb)

2022-02-24 23:06 UTC, FernandoCiballero commented on app/controllers/api/v1/auth_controller.rb
> +          render json: @user.as_json(only: %i[email first_name last_name role_id])
Tendrias que crear un serializer para `@user`, y te faltaría agregar el atributo `status` al metodo `render`.

2022-02-24 23:09 UTC, FernandoCiballero commented on app/controllers/api/v1/auth_controller.rb
> +        @user ||= User.find_by(email: params.require(:email))
Teniendo el `exception handler`, puede usar find para arrojar una excepción en caso de que el usuario no exista.
```suggestion
        @user ||= User.find(email: params.require(:email))
```

2022-02-24 23:14 UTC, FernandoCiballero commented on app/controllers/api/v1/users_controller.rb
> +        params.permit(:email, :password, :first_name, :last_name)
El `require` es necesario para capturar la excepción de `ActionController::ParameterMissing`
[Documentación](https://api.rubyonrails.org/classes/ActionController/Parameters.html#method-i-require)

2022-02-24 23:18 UTC, FernandoCiballero requested changes
Muy bien!!! te dejo unos comentarios con algunas mejoras.

2022-02-25 13:51 UTC, chocolatito commented on app/controllers/api/v1/users_controller.rb
> +        params.permit(:email, :password, :first_name, :last_name)
Acabo de descubrir dos cosas respecto a esto:
1. El ticket no me pedía modificar el `user_controller.rb`, así que esto no debería ir.
2. En la captura de pantalla, se muestra que `params.require(:user)` nunca permitiría que llegue el valor de `:password` porque ya no existe esa columna en la tabla, sin embargo, al usar `:password_digest` (la columna existente) y acomodando la validación en el modelo, se anula el `has_secure_password` y a contraseña se almacena en texto plano. obteniendo lo siguiente:
```
{
    "id": 4,
    "email": "zzz@example.ioo",
    "first_name": "first_name",
    "last_name": "last_name",
    "discarded_at": null,
    "created_at": "2022-02-25T13:38:25.026Z",
    "updated_at": "2022-02-25T13:38:25.026Z",
    "role_id": 1,
    "password_digest": "password"
}
```

![user_params](https://user-images.githubusercontent.com/42852456/155725147-6ad9c51f-e531-4d79-8d9c-8c1304802a5b.png)  

En fin, sigo trabajando

2022-02-25 14:12 UTC, chocolatito commented on app/controllers/api/v1/auth_controller.rb
> +        @user ||= User.find_by(email: params.require(:email))
No queda claro, porque se sugiere modificar `User.find` (solo busca por el valor de ID) por `User.find_by`.

2022-02-25 23:01 UTC, chocolatito commented on app/controllers/api/v1/auth_controller.rb
> +
Realizado. Se implementa en archivo `app/controllers/concerns/exception_handler.rb`

2022-03-04 16:27 UTC, lautarograc approved these changes
Genial! Me parece casi listo para mergear. Quedaría perfecto

2022-03-05 22:41 UTC, FernandoCiballero approved these changes
Buen Laburo!!! :rocket:

2022-03-05 22:44 UTC, merged