feat/OT151-39: add endpoint POST /categories
alkemyTech/OT151-SERVER pull request #17
Opened 2022-02-24 17:22 UTC by chocolatito

---
### Resumen

---
Los archivos de la rama `main` modificados
- **app/controllers/api/v1/categories_controller.rb**: Agrega la acción `create` para agregar una nueva categoria.
- **config/routes.rb**: Añade el Endpoint _categories_ al espacio de nombres.

---
Nuevos archivos
- **app/serializers/category_serializer.rb**: Archivo generado por el comando `rails g serializer Category name description`

### Comentatio/s:
Seria recomendable añadir una restricción de unicidad para la columna `name` correspondiente a la tabla `Categories`.

2022-02-24 23:20 UTC, FernandoCiballero commented on app/controllers/api/v1/categories_controller.rb
> +        @category = Category.new(category_params)
Acá también podes usar el exception handler que te comenté en el otro PR y usar directamente:
```suggestion
        @category = Category.create!(category_params)
```

2022-02-24 23:21 UTC, FernandoCiballero requested changes
Muy bueno Ivan!!! te dejo unos comentarios para introducir un par de mejoras.

2022-03-03 22:14 UTC, chocolatito commented
Elimine todos los archivos que no son relevantes al ticket.

2022-03-04 18:59 UTC, lautarograc approved these changes
Lo veo bien! Sin mucho que añadir

2022-03-05 22:46 UTC, FernandoCiballero approved these changes
Muy bueno Ivan!!!

2022-03-05 22:49 UTC, merged