feat/OT151-27: add migration and model for slide
alkemyTech/OT151-SERVER pull request #18
Opened 2022-02-26 00:50 UTC by chocolatito

### Resumen

---
Los archivos de la rama `main` modificados en este branch
- **db/schema.rb**: Modificado al ejecutar las migraciones.

---
Nuevos archivos
- **app/models/slide.rb**: Correspondiente al modelo.
- **db/migrate/**
  + **20220224194045_create_slides.rb**: Crea la tabla `slides`, define la referencia a la tabla `organizations` y se propone como indice con restricción de unicidad entre los valores de las columnas `organization_id` y `order` (_slides_ de una misma _organización_, no pueden tener el mismo número _orden_).
  + **20220224201414_add_discarded_at_to_slides.rb**: Para implementar _soft delete_ provisto por la gema discard.
- **spec/factories/slides.rb**
- **spec/models/slide_spec.rb**

### Comentario/s:
El modelo establece la restricción de
> *no persistir una instancia de **Slide** sin que este tenga adjunto una imagen*  
mediante la definición de del validator `check_image_presence`.

El modelo ***Annuncement*** también implemente este método, se propone realizar una _refactor_ de este método en el futuro.

2022-03-01 02:47 UTC, FernandoCiballero commented on app/models/organization.rb
>    validates :name, presence: true,
Sería conveniente no agregar cambios en partes de código que no corresponden al ticket. En este caso lo ideal sería hacer un `fix` con las mejoras al código.

2022-03-01 02:50 UTC, FernandoCiballero commented on spec/models/slide_spec.rb
> +    it { is_expected.to have_db_column(:updated_at).of_type(:datetime) }
Se podría agregar el test de los indices [https://github.com/thoughtbot/shoulda-matchers#activerecord-matchers](https://github.com/thoughtbot/shoulda-matchers#activerecord-matchers)

2022-03-01 02:51 UTC, FernandoCiballero requested changes
Muy bien Ivan!!! te dejo algunas cosas que podrias modificar.

2022-03-02 00:38 UTC, chocolatito commented on app/models/organization.rb
>    validates :name, presence: true,
Entendido

2022-03-04 18:57 UTC, lautarograc approved these changes
Lo vi bien! No tengo nada para comentar

2022-03-05 20:48 UTC, FernandoCiballero commented
Muy buen trabajo Ivan!!! :+1: muy prolijo todo.

2022-03-05 20:48 UTC, FernandoCiballero approved these changes

2022-03-05 20:48 UTC, merged