Added module for authentication
alkemyTech/OT151-SERVER pull request #19
Opened 2022-02-26 22:03 UTC by lautarograc

En base al [ticket 21](https://alkemy-labs.atlassian.net/browse/OT151-24?atlOrigin=eyJpIjoiYTQ2NWU4ZDljYmY4NDcwYmE5Y2U4YzNmMTI2YTFhZDAiLCJwIjoiaiJ9):

2022-03-01 02:55 UTC, FernandoCiballero reviewed
Muy bueno Lautaro!!! 👍 quedaría listo para mergear y probarlo durante la implementación en los controladores.

2022-03-03 20:07 UTC, chocolatito requested changes

2022-03-04 17:57 UTC, chocolatito submitted a review, later dismissed
Aprobado

2022-03-05 21:39 UTC, FernandoCiballero approved these changes
Muy buena la modularización Lautaro!!! :+1:

2022-03-05 21:41 UTC, FernandoCiballero approved these changes

2022-03-05 21:44 UTC, merged