feat OT151-15: add model migration and controller for organization
alkemyTech/OT151-SERVER pull request #2
Opened 2022-02-18 04:25 UTC by chocolatito

### Se añaden las siguientes gemas:  
- [**discard**](https://github.com/jhawthorn/discard):  
Para implementar _soft delete_. Se reemplaza `organizatión.destroy` por `organizatión.discard` y `Organizatión.all` por `Organizatión.kept`. La migración _20220218031746_add_discarded_at_to_organizations.rb_ añade la columna necesaria para implementar _soft delete_.  
- [**kaminari**](https://github.com/kaminari/kaminari):  
Para implementar paginación. El tamaño de pagina por defecto es de 25 instancias, puede modificarse modificando el método `per_page` del archivo _app/controllers/concerns/paginable.rb_. Para personalizar el tamaño de pagina para un modelo, añadir `max_paginates_per` en el modelo.

---
### Versionado de Api
Se utiliza la estructura de directorio `/api/v1/organizations`. El codigo del controlador sigue el patron generado por el comando:
```sh
rails g scaffold_controller Api::V1::organizations
```
---
### Serializers
Se generan dos clases serializer:
- **OrganizationsSerializer**  
Para serializar la colección retornada en la acción `#index`. Solo serializa solamente los atributos `:name` y `:email` por poseer la restricción `NOT NULL`, sin embargo se prefiere no serializar `welcome_text` por ser del tipo `TEXT` y prevenir un excesivo consumo de ancho de banda pese al limite de la paginación.
- **OrganizationSerializer**:  
Para serializar todos los atributos de registros individuales para las acciones `#show`, `#create` y `#update`.

2022-02-18 16:04 UTC, lautarograc approved these changes
Me gustó mucho la estrategia de serialización. 

Algunas líneas de comentario ayudarían a entender mejor la lógica, sobre todo en lo relacionado a la paginación.

2022-02-18 17:28 UTC, FernandoCiballero commented
En lineas generales:
* No se solicita paginación en este ticket(esta contemplada en un ticket más adelante), asi que deberias remover la configuración de `Kaminari`.
* Solo se pide el controlador base(crear el archivo nada más), despues iremos agregando en la medida de lo necesario los endpoints correspondientes.
* Los test que habitualmente se utilizan son: `model`, `request` y se pueden testear los helpers creados en algun concern. En todo caso solo corresponderia ahora los test de `model` si queres agregarlos.

2022-02-20 14:45 UTC, FernandoCiballero commented on .gitignore
> +organizations_serializer copy.rb
Convendría que remuevas estos archivos del proyecto, en vez de usar `gitignore` ya que puede ser confuso en un futuro. Una muy buena opcion es use [gist](https://gist.github.com/).

2022-02-20 14:54 UTC, FernandoCiballero commented on .gitignore
> +paginable copy.rb
Por favor 🙏 revisar la configuración de EOF en tu IDE, te paso la solución para [VS Code](https://stackoverflow.com/questions/44704968/visual-studio-code-insert-new-line-at-the-end-of-files).

2022-02-20 15:14 UTC, FernandoCiballero commented on db/migrate/20220218031735_create_organizations.rb
> +      t.integer :phone
Podriamos agregar address y phone como null: false tambien.

2022-02-20 15:29 UTC, chocolatito commented on .gitignore
> +organizations_serializer copy.rb
Es verdad. Removí los archivos en el local, pero me olvide de cambiar el _.gitignore_, solo lo modifique para probar algo antes de hacer el push.

2022-02-20 15:36 UTC, FernandoCiballero commented on spec/factories/organizations.rb
> +    image_url { "MyString" }
En el factory puedes usar `faker` para definir datos de prueba.

2022-02-20 15:39 UTC, FernandoCiballero commented on spec/routing/api/v1/organizations_routing_spec.rb
> +require "rails_helper"
Deberias eliminar este archivo ya que las rutas las probamos en los `request specs`.

2022-02-20 15:41 UTC, FernandoCiballero commented on spec/requests/api/v1/organizations_spec.rb
> +  # This should return the minimal set of attributes required to create a valid
Este archivo deberia quedar vacio hasta que se cree un endpoint
```suggestion
  RSpec.describe "/api/v1/organizations", type: :request do
  end
```

2022-02-20 15:43 UTC, FernandoCiballero commented on app/controllers/api/v1/organizations_controller.rb
> +end
Te sugiero ejecutar `bundle exec rubocop` ya que te vas a encontrar con varias `offenses` para resolver.

2022-02-20 15:44 UTC, FernandoCiballero requested changes
Te dejo unas sugerencias y correcciones para hacer.

2022-02-20 15:51 UTC, chocolatito commented on db/migrate/20220218031735_create_organizations.rb
> +      t.integer :phone
Por lógica, siempre se debería poner como restricción que:
> no se registre una organización sin que proporcionen un teléfono y dirección.  Incluso, en algunos sistemas de administración, se pone por defaul 0.

No obstante, en el ticket especifica **explicitamente** que deben ser `NULLABLE`:
```
id: INTEGER NOT NULL AUTO_INCREMENT
name: VARCHAR NOT NULL
address: VARCHAR NULLABLE
phone: INTEGER NULLABLE
email: VARCHAR NOT NULL
welcomeText: TEXT NOT NULL
. . .
```

A menos que establezcamos esa salvedad para el propósito de la aceleración, creo que no deberíamos modificar los requerimientos y hacer formular un nuevo ticket para implementar los cambios en otro sprint.

En cualquier caso, me ajusto a lo que me indiques.

2022-02-20 15:53 UTC, chocolatito commented on spec/factories/organizations.rb
> +    image_url { "MyString" }
Entendido. Como no realice specs para el modelo **Organization**, simplemente no modifique los factories generados.

2022-02-20 15:53 UTC, chocolatito commented on spec/routing/api/v1/organizations_routing_spec.rb
> +require "rails_helper"
Entendido

2022-02-20 15:53 UTC, chocolatito commented on spec/requests/api/v1/organizations_spec.rb
> +  # This should return the minimal set of attributes required to create a valid
Entendido

2022-02-20 15:54 UTC, chocolatito commented on app/controllers/api/v1/organizations_controller.rb
> +end
Entendido

2022-02-21 03:54 UTC, FernandoCiballero commented on db/migrate/20220218031735_create_organizations.rb
> +      t.integer :phone
Perfecto, lo dejamos así. Quedaría solamente modificar el campo email para que sea `unique`.

2022-02-21 03:55 UTC, FernandoCiballero commented on spec/factories/organizations.rb
> +    image_url { 'MyString' }
Podrias usar faker acá para generar datos aleatorios.

2022-02-21 03:56 UTC, FernandoCiballero commented on spec/models/organization_spec.rb
> +  pending "add some examples to (or delete) #{__FILE__}"
Podrias agregar los test al modelo tal como sugerí por slack.

2022-02-21 03:57 UTC, FernandoCiballero commented on spec/requests/api/v1/organizations_spec.rb
> +# end
En principio no haría falta comentar estas lineas.

2022-02-21 03:59 UTC, FernandoCiballero commented on Gemfile
> +gem 'discard' # https://rubygems.org/gems/discard
Faltaría modificar esta linea como te indique anteriormente(debajo de la linea 11).

2022-02-21 04:00 UTC, FernandoCiballero requested changes
Te dejé unas cosas que quedaron sin corregir.

2022-02-24 02:44 UTC, closed without merging