Setup Amazon S3 SDK for Active Storage in production
alkemyTech/OT151-SERVER pull request #21
Opened 2022-02-28 16:32 UTC by lautarograc

Añadida la configuración de Amazon S3 para el upload de archivos de active storage. Solo afecta al ambiente de producción. 
Se maneja mediante la gema de S3 del SDK de AWS para Ruby.

Queda pendiente agregar la configuración de servicio con el nombre del bucket y con las credenciales que aún no han sido provistas.

2022-03-01 03:06 UTC, FernandoCiballero requested changes
Muy bien Lautaro!!! 👍 faltaría agregar al archivo `.env.sample` las variables de entorno del bucket S3. Las variables se llaman `BUCKET NAME`,`PUBLIC KEY` y `SECRET KEY`. Les paso por slack el valor que deben completar en cada variable.

2022-03-03 00:49 UTC, chocolatito requested changes

2022-03-03 00:49 UTC, chocolatito commented on Gemfile
> +gem 'aws-sdk-s3', '~> 1.113' # https://rubygems.org/gems/aws-sdk-s3
Faltaría acomodar la gema en por orden alfabético desde la linea 11

2022-03-03 00:49 UTC, chocolatito commented on config/environments/production.rb
> +  config.active_storage.service = :amazon
Creo que para cumplir con el requerimiento del ticket esta faltando modificar el archivo [`storage.yml`](https://github.com/alkemyTech/OT151-SERVER/blob/config/OT151-36-Amazon-S3/config/storage.yml#L10) para utilizar las variables de entorno del `.env`.
Preferentemente, en lugar de `amazon`, deberíamos usar el nombre del servicio `s3` en la opción de almacenamiento (L10 de [`storage.yml`](https://github.com/alkemyTech/OT151-SERVER/blob/config/OT151-36-Amazon-S3/config/storage.yml#L10))

2022-03-03 18:40 UTC, lautarograc commented
Editado storage.yml para incluir las variables de entorno y ordenada la gema del SDK en la gemfile!

2022-03-03 20:15 UTC, chocolatito approved these changes
Listo

2022-03-05 21:32 UTC, FernandoCiballero reviewed
Muy bien Lautaro!!! le agregue las variables de entorno al archivo .env.sample para que esten disponibles para todo el equipo.

2022-03-05 21:35 UTC, merged