feat/OT151-35: add endpoint post organization/public
alkemyTech/OT151-SERVER pull request #22
Opened 2022-02-28 23:12 UTC by chocolatito

### Resumen

---
Los archivos de la rama `main` modificados
- **Gemfile**: Añade la gema jwt
- **app/controllers/application_controller.rb**: Incluye los módulos `Authenticable` y `Authorized` que intervienen en la autorizacion y `ExceptionHandler` para manejar excepciones.
- **app/controllers/api/v1/organizations_controller.rb**: Agrega la acción `create` para agregar una nueva organización.
- **config/routes.rb**: Añade el Endpoint _/organization/public_ al espacio de nombres.

---
Nuevos archivos
- **app/serializers/organization_serializer.rb**: Archivo generado por el comando `rails g serializer organization email name welcome_text address phone about_us_text`
- **app/controllers/concerns/**
  + **exception_handler.rb**: Manejador de excepciones.
  + **authenticable.rb**: Verifica si el usuario inicia ha iniciado sesion y obtiene el `@current_user`. ***Este es un archivo de soporte, implementa requerimientos de otro/s ticket/s necesarios***. 
  + **authorized.rb**: Implementa el mecanismo de autorización para garantizar que solo un usuario con rol de ***admin*** pueda agregar una categoría nueva al sistema. ***Este es un archivo de soporte, implementa requerimientos de otro/s ticket/s necesarios***.
- **app/lib/json_web_token.rb**: Clase responsable de generar el token y decodificarlo. ***Este es un archivo de soporte, implementa requerimientos de otro/s ticket/s necesarios***.

---
### Comentario/s:
- Generar token
Si ya existen usuario en la db, se puede generar el token con los siguientes comandos
```
$ rails c
Running via Spring preloader in process 27202
Loading development environment (Rails 6.1.4.6)
[1] pry(main)> JsonWebToken.encode(user_id: 1)
=> "eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDYxNDY2NjF9.CzpEHN5mBBhRl_x7s5AGYo99DF_0qmjFPptN3fSMvI0"
[2] pry(main)> JsonWebToken.encode(user_id: 2)
=> "eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDYxNDY2NjZ9.m98_oT2usV8O8SdjCp6oYOGm-NntOLI5XZKpp3sbzrI"
```

> NOTA: Se asume que solo uno de los dos usuarios de `id` igual a `1` o `2` es administrador.

- Proteger el los endpoints  
Actualizar el controlador de users
```
# app/controllers/api/v1/users_controller.rb
module Api
  module V1
    class UsersController < ApplicationController
      before_action :authorize_request, except: :create
      before_action :ownership?, except: :create
      # [...]
    end
  end
end
```

2022-03-01 03:10 UTC, FernandoCiballero commented on app/controllers/concerns/exception_handler.rb
> +  def four_twenty_two(errors)
Me parece más descriptivo un `handle_record_invalid` como nombre para este método.

2022-03-01 03:11 UTC, FernandoCiballero requested changes
Muy bueno Ivan!!! 👍 te dejo un comentario para arreglar una cosa.

2022-03-03 18:32 UTC, lautarograc commented on app/lib/json_web_token.rb
> +class JsonWebToken
[Corresponde al ticket 29](https://alkemy-labs.atlassian.net/browse/OT151-29?atlOrigin=eyJpIjoiMjc3YjY1YmJmNTM1NGQ1MWFiNGI1NzczZTRhNDcxOTIiLCJwIjoiaiJ9)

2022-03-03 18:33 UTC, lautarograc reviewed
En principio me parece que está bien para el merge, pero se están pisando tickets que le corresponden a otros colaboradores.

2022-03-03 19:35 UTC, Tinix commented on app/lib/json_web_token.rb
> +class JsonWebToken
me parece que esta bien, se puede pisar con otro ticket pero todo se arregla la buena intencion es la cuenta.

2022-03-03 20:17 UTC, chocolatito commented on app/lib/json_web_token.rb
> +class JsonWebToken
La idea es que la parte que se pisa, se reemplace directamente con la implementación del ticket que le corresponde. Asi ya estan creadas las carpetas y hacemos coincidir los nombres de clases y métodos para prevenir algún que otro conflicto.

2022-03-03 22:38 UTC, chocolatito commented
Actualizado. Se eliminaron los archivos no relevantes al ticket

2022-03-04 19:01 UTC, lautarograc approved these changes
Cumple bien con el ticket

2022-03-05 22:50 UTC, FernandoCiballero approved these changes
Muy Bueno!!! :rocket:

2022-03-05 22:57 UTC, merged