feat/OT151-29 Añadir lógica de JWT
alkemyTech/OT151-SERVER pull request #23
Opened 2022-02-28 23:28 UTC by Tinix

COMO usuarioQUIERO estar autenticado en la plataformaPARA poder acceder a todos sus servicios.

Criterios de aceptación:

Cuando el usuario se autentica, el servidor deberá generar un JSON Web Token con los datos del usuario, y devolver el mismo en la respuesta.

Para validar que el usuario está autenticado, el servidor deberá desencriptar este token, obteniéndolo del encabezado Authorization de la petición recibida.

Guia: https://medium.com/binar-academy/rails-api-jwt-authentication-a04503ea3248

2022-03-01 03:14 UTC, FernandoCiballero commented on app/controllers/api/v1/users_controller.rb
> +        params.permit(:email, :password, :first_name, :last_name)
Es método `require` debería estar para lanzar la excepción.
```suggestion
        params.require(:user).permit(:email, :password, :first_name, :last_name)
```

2022-03-01 03:17 UTC, FernandoCiballero requested changes
Muy bueno Daniel!!! deberías revisar los PR de Lautaro e Ivan ya que la autenticación y Token estaban modularizadas fuera de los controladores.

2022-03-01 03:23 UTC, FernandoCiballero commented on config/routes.rb
> +      get '/*a', to: 'application#not_found'
Cual sería el propósito de crear esta ruta? 
```ruby
get '/*a', to: 'application#not_found'
```

2022-03-01 03:24 UTC, FernandoCiballero requested changes
Buen trabajo!!! 👍  dejo un par de comentarios.

2022-03-02 22:22 UTC, MatiasDevJam commented on Gemfile
> +gem 'jwt', '~> 2.3'
Te sugiero que ordenes las gemas alfabéticamente y le agregues su respectivo link a la documentación.

2022-03-02 22:24 UTC, chocolatito requested changes
Creo que el cambio obligatorio seria el del Gemfile porque es lo que habíamos convenido para el proyecto.

Seria recomendable que reutilices la implementación del PR#16 que implementa la logica para el login con los correspondientes módulos para manejar excepciones.

No creo que sea necesario modigicar el archivo `app/controllers/api/v1/users_controller.rb` ya que para este ticket basta con tener un usuario creado desde la consola de rails.

2022-03-02 22:24 UTC, chocolatito commented on app/controllers/api/v1/authentication_controller.rb
> +end
Podrías integrar los archivos del [PR 16](https://github.com/alkemyTech/OT151-SERVER/pull/16/files#diff-4c3d6d2255321d6b4402d3016c1831428e515f09c3e5c437de3f03565c44e9bc) que implementa el login y ya esta revisado y corregido.

2022-03-02 23:50 UTC, MatiasDevJam commented on config/routes.rb
>  end
Suguiero quitar estos cambios.

2022-03-02 23:51 UTC, MatiasDevJam commented on app/controllers/api/v1/authentication_controller.rb
> +end
Sugiero quitar estos cambios, ya que están contemplados en otro ticket.

2022-03-02 23:54 UTC, MatiasDevJam commented on app/controllers/api/v1/users_controller.rb
> +        params.permit(:email, :password, :first_name, :last_name)
Sugiero quitar estos cambios, están contemplados en otro ticket.

2022-03-02 23:55 UTC, MatiasDevJam commented on app/controllers/application_controller.rb
> +  end
Sugiero quitar estos cambios.

2022-03-02 23:55 UTC, MatiasDevJam commented on config/routes.rb
> +      get '/*a', to: 'application#not_found'
Sugiero quitar estos cambios.

2022-03-02 23:59 UTC, MatiasDevJam requested changes

2022-03-02 23:59 UTC, MatiasDevJam commented on config/routes.rb
> +      get '/*a', to: 'application#not_found'
Sugiero quitar estos cambios.

2022-03-03 00:54 UTC, chocolatito requested changes

2022-03-03 00:54 UTC, chocolatito commented on config/routes.rb
> +      get '/*a', to: 'application#not_found'
Me surge la siguiente duda.
> _**¿Una API Restfull tiene necesidad de redireccionar a otro endpoint?**_

En dicho caso, creo que para el propósito del usuario es _consumir_ los recursos, y no _navegar_

Entonces, la linea 8 no correspondería para este sistema.

2022-03-03 14:52 UTC, Tinix commented on config/routes.rb
> +      get '/*a', to: 'application#not_found'
el proposito seria evitar que algun usuario curioso este chequeando otro tipo de ruta alternativa, la escribi y me habia faltado el metodo.. pero si no es necesario la eleminamos, no hay problema.

2022-03-03 14:53 UTC, Tinix commented on Gemfile
> +gem 'jwt', '~> 2.3'
perfecto , gracias!

2022-03-03 14:56 UTC, Tinix commented on config/routes.rb
> +      get '/*a', to: 'application#not_found'
si tal cual respondi mas arriba, esa linea cumple otro proposito que no esta contemplado en el ticket , no hoy problema se saca la linea 8.

2022-03-04 00:07 UTC, lautarograc requested changes

2022-03-04 00:07 UTC, lautarograc commented on app/controllers/api/v1/authentication_controller.rb
> +                         username: @user.username }, status: :ok
Ojo! Esta línea rompe el código por que no existe "username" dentro de la base de datos.
Si se elimina esa línea, la request funciona como se espera.
 
 `
curl --location --request POST 'localhost:3000/api/v1/auth/login' \
--header 'Content-Type: application/json' \
--data-raw '{"email":"email@email.com", "password":"app123"}'
`

2022-03-05 23:11 UTC, merged