Feat/ot151 25 modulo autorizacion
alkemyTech/OT151-SERVER pull request #24
Opened 2022-02-28 23:48 UTC by Tinix

COMO usuario administradorQUIERO restringir el acceso a cierto contenidoPARA mantener los datos protegidos 

Criterios de aceptación:Deberá verificar el campo roleId, y permitir continuar si el usuario tiene rol correspondiente a administrador 

Aclaracion: este modulo ya lo habia hecho el otro Daniel , solamente cambie la parte de role_id = 1 para el Admin, pero lo ultima palabra la tiene el PM.

2022-03-02 21:10 UTC, FernandoCiballero commented on Gemfile
> +gem 'jwt', '~> 2.3'
Te suguiero poner la gema en orden alfabético con el correpondiente link

2022-03-02 21:11 UTC, FernandoCiballero requested changes
Hola Daniel, te deje unos comentarios para revisar!!!

2022-03-03 00:59 UTC, chocolatito requested changes

2022-03-03 19:58 UTC, Tinix commented on Gemfile
> +gem 'jwt', '~> 2.3'
si tenes razon corri ordinare Gemfile y no ordeno nada, ahora probe otra solucion mas rapida.

2022-03-05 23:28 UTC, closed without merging