Feat/ot151 32 user update endpoint
alkemyTech/OT151-SERVER pull request #27
Opened 2022-03-02 18:12 UTC by lautarograc

Añadido el endpoint y su correspondiente ruta para actualizar los datos del usuario. Para autorizar la actualización, el controlador exige que lo haga el usuario autenticado actual (current_user). Podría ser recomendable (aunque no este sugerido en el ticket) que los administradores puedan actualizar remotamente el perfil de todos los demás usuarios.

2022-03-03 02:13 UTC, chocolatito requested changes

2022-03-03 02:13 UTC, chocolatito commented on app/controllers/api/v1/users_controller.rb
>        def user_params
Ya lo he comentado [aqui](https://github.com/alkemyTech/OT151-SERVER/pull/16#discussion_r814783367)
```
params.require(:user).permit(:email, :password, :first_name, :last_name)
```
termina por filtrarme el valor de `:password`
Ya lo probé en el debug y `params.require(:user)` no admite ningún parámetro que no corresponda con los nombres de las columnas de la tabla `users` (incluso admite `:created_at`, `:updated_at`)

Para comprobarlo use
```
  def user_params
    binding.pry
    # {"email":"aaa@email.com", "password":"password", "first_name":"first_name", "last_name":"last_name"}
    params.require(:user).permit(:email, :password, :first_name, :last_name)
  end
```
Por lo que entiendo en la [documentación](https://api.rubyonrails.org/classes/ActionController/Parameters.html), el `params` es un objeto `ActionController::Parameters` y se construye en base a la definición de la tabla del recurso. En este caso, la tabla ya no contiene la columna `password` porque fue removida.

2022-03-03 17:55 UTC, lautarograc commented on app/controllers/api/v1/users_controller.rb
>        def user_params
Buenas Ivan. Disculpame pero no termino de entender bien el problema. Estuve testeando con cURL y me produce los resultados esperados. 
`
curl -v   -H "Accept: application/json"   -H "Content-type: application/json"   -X POST   -d ' {"user":{"first_name":"firstname","last_name":"lastname","email":"email@email.com","password":"app123", "role_id":1}}'   http://localhost:3000/api/v1/auth/register
`
En el servidor genera esta respuesta:
`
 User Create (2.2ms)  INSERT INTO "users" ("email", "first_name", "last_name", "created_at", "updated_at", "role_id", "password_digest") VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING "id"
`
Y en la base de datos se crea un usuario tal que:
`
#<User:0x00007f4c9c214360
  id: 2,
  email: "email@email.com",
  first_name: "firstname",
  last_name: "lastname",
  discarded_at: nil,
  created_at: Thu, 03 Mar 2022 17:42:43.115860000 UTC +00:00,
  updated_at: Thu, 03 Mar 2022 17:42:43.115860000 UTC +00:00,
  role_id: 1,
  password_digest: "[FILTERED]">]

`
BCrypt interpreta password como password_digest. Antes de introducir la contraseña en la base de datos, bcrypt incluye el cost, salt y hash en el digest de los modelos con secure password,  por lo que en teoría no se podría almacenar una contraseña no encriptada.

2022-03-03 18:55 UTC, chocolatito commented on app/controllers/api/v1/users_controller.rb
>        def user_params
Me resulta muy raro lo que acabas de mostrar, partiendo del hecho de que estas enviando al servidor `"role_id":1`.

Sin embargo, en la linea 28 del código, no estas admitiendo el parámetro `:role_id`
```
params.require(:user).permit(:email, :password, :first_name, :last_name)
```

2022-03-03 19:00 UTC, lautarograc commented on app/controllers/api/v1/users_controller.rb
>        def user_params
> Me resulta muy raro lo que acabas de mostrar, partiendo del hecho de que estas enviando al servidor `"role_id":1`.
> 
> Sin embargo, en la linea 28 del código, no estas admitiendo el parámetro `:role_id`
> 
> ```
> params.require(:user).permit(:email, :password, :first_name, :last_name)
> ```

Lo agregué moméntaneamente para probar el curl. De todas maneras, deberíamos asignar un rol default en la creación de nuevos usuarios.

2022-03-03 20:57 UTC, chocolatito requested changes

2022-03-03 20:57 UTC, chocolatito commented on app/controllers/api/v1/users_controller.rb
> +          render json: { errors: user.errors }, status: :unprocessable_entity
Error de tipeo, es `@user.errors`

2022-03-03 20:57 UTC, chocolatito commented on app/controllers/api/v1/users_controller.rb
> +        @user = current_user
Encuentro un conflicto en el caso de que el daministrador quiera editar el registro de otro usuario, terminaria editando su propio registro (de administrador).. necesariamente va a hacer falta la funcion `find_user` o `set_user` encargada de inicializar la variable de instancia `@user`

2022-03-04 18:29 UTC, chocolatito requested changes
Lo mas urgente seria el archivo del serializer y borrar la linea 9. Lo de las excepciones se podria dejar pasar para un fix, aunque es mejor si se hace ahora.

2022-03-04 18:29 UTC, chocolatito commented on app/controllers/api/v1/users_controller.rb
> +          render json: UserSerializer.new(@user).serializable_hash.to_json
Falta el archivo del serializer (`app/serializers/user_serializer.rb`)

2022-03-04 18:29 UTC, chocolatito commented on app/controllers/api/v1/users_controller.rb
> +        if @user.update(user_params)
En otros PR nos recomiendan usar los metodos terminados en `!` para levantar la excepción.
En este caso, le corresponde una excepción del tipo `ActiveRecord::RecordInvalid`
```
@user.update!(user_params)
```
>NOTA: Necesita tener un manejador de excepciones, por ejemplo: [app/controllers/concerns/exception_handler.rb](https://github.com/alkemyTech/OT151-SERVER/pull/16/files#diff-908485b11e8cd13adb591f614b648cbc6b3223d47d97e86e4ab25ea6c3396c85)

2022-03-04 18:29 UTC, chocolatito commented on app/controllers/api/v1/users_controller.rb
> +        @user = User.find(params[:id])
En otros PR nos recomiendan usar los métodos terminados en ! para levantar la excepción.
En este caso, le corresponde una excepción del tipo `ActiveRecord::RecordNotFound`
```
@user = User.find!(params[:id])
```

2022-03-04 18:29 UTC, chocolatito commented on app/controllers/api/v1/users_controller.rb
> +      before_action :ownership?, only: %i[update]
De acuerdo a lo comentado en la ultima Daily. Esta linea se debe borrar

2022-03-04 18:32 UTC, lautarograc commented on app/controllers/api/v1/users_controller.rb
> +          render json: UserSerializer.new(@user).serializable_hash.to_json
Buenas. Decidí no incluirlo por que ya lo incluiste vos en el [PR 16](https://github.com/alkemyTech/OT151-SERVER/pull/16/files). Lo puedo incluir acá tambien, no hay drama!

2022-03-04 18:36 UTC, chocolatito commented on app/controllers/api/v1/users_controller.rb
> +          render json: UserSerializer.new(@user).serializable_hash.to_json
Mientras sean iguales y coincidan todas las lineas (copy & paste), creo que no produce conflicto en la mezcla

2022-03-04 18:49 UTC, lautarograc reviewed
Corregido con lo sugerido por @chocolatito

2022-03-04 19:25 UTC, chocolatito requested changes
Descargue y probé todo tal cual esta, tengo dos problemas
- no funciona cuando solamente se quiere actualizar el `password`. Me retorna lo siguiente:
> {
    "error": "param is missing or the value is empty: user\nDid you mean?  user\n               password\n               format\n               controller"
}    

- Cuando envió algún paramento adicional o todos (`{"email":"email@mail.com", "password":"password","first_name":"aaafirst_name", "last_name":"last_name"}`) me falla la validación del modelo.
> {
    "message": "Validation failed: Password can't be blank, Password is too short (minimum is 6 characters)"
}

Lo que significa que hay que modificar el la validación del modelo.
Dejo la siguiente captura si quieres intentar en la consola de rails.
![falla-update](https://user-images.githubusercontent.com/42852456/156828587-f3382d1a-42c0-4a22-bda0-c3398a8846e4.png)

2022-03-04 19:25 UTC, chocolatito commented on app/controllers/api/v1/users_controller.rb
> +        @user = User.find!(params[:id])
Me equivoco en la peticion anterior.
El método correcto es
```
@user = User.find_by!(id: params[:id])
```

2022-03-04 19:25 UTC, chocolatito commented on app/controllers/api/v1/users_controller.rb
> +        end0
Error de tipe

2022-03-04 19:48 UTC, lautarograc commented
> Descargue y probé todo tal cual esta, tengo dos problemas
> 
> * no funciona cuando solamente se quiere actualizar el `password`. Me retorna lo siguiente:
> 
> > {
> > "error": "param is missing or the value is empty: user\nDid you mean?  user\n               password\n               format\n               controller"
> > }
> 
> * Cuando envió algún paramento adicional o todos (`{"email":"email@mail.com", "password":"password","first_name":"aaafirst_name", "last_name":"last_name"}`) me falla la validación del modelo.
> 
> > {
> > "message": "Validation failed: Password can't be blank, Password is too short (minimum is 6 characters)"
> > }
> 
> Lo que significa que hay que modificar el la validación del modelo. Dejo la siguiente captura si quieres intentar en la consola de rails. ![falla-update](https://user-images.githubusercontent.com/42852456/156828587-f3382d1a-42c0-4a22-bda0-c3398a8846e4.png)

No estoy logrando reproducir el error. Al probar desde la consola, me devuelve resultados esperados:
![Screenshot from 2022-03-04 16-46-36](https://user-images.githubusercontent.com/78238453/156831468-9719b390-c72e-4ec2-b0a0-bbbe59e433c5.png)
y con el cURL: 
`
curl --location --request PATCH 'localhost:3000/api/v1/users/1' \
--header 'Content-Type: application/json' 
--data-raw '{"user":{"first_name":"update_test", "password":"password123"}}'
`
recibo: 
`
    "data": {
        "id": "1",
        "type": "user",
        "attributes": {
            "email": "example@mail.com",
            "first_name": "update_test",
            "last_name": "example",
            "role_id": 1
        }
    }
}
`

2022-03-04 21:45 UTC, chocolatito submitted a review, later dismissed
Probado y funcionando

2022-03-06 00:02 UTC, FernandoCiballero approved these changes

2022-03-06 00:02 UTC, merged