Feat/ot 151 40 endpoint update categories
alkemyTech/OT151-SERVER pull request #28
Opened 2022-03-02 18:13 UTC by lautarograc

Añadido el endpoint y ruta correspondiente para actualizar los parametros de las categorías. Solo disponible para usuarios adminsitradores.

2022-03-03 02:16 UTC, chocolatito requested changes

2022-03-03 02:16 UTC, chocolatito commented on app/controllers/concerns/authorized.rb
> +    @current_user.role.name == 'admin'
Lo unico que estaría faltando, es contemplar la excepción (con el `status: :forbidden`), ya que este método solo devuelve `true` o `false`.

2022-03-03 18:12 UTC, lautarograc commented on app/controllers/concerns/authorized.rb
> +    @current_user.role.name == 'admin'
> Lo unico que estaría faltando, es contemplar la excepción (con el `status: :forbidden`), ya que este método solo devuelve `true` o `false`.

Claro! De todas formas, en el merge con tu ticket se completa con la demás lógica

2022-03-03 19:46 UTC, Tinix commented on app/controllers/concerns/authorized.rb
> +    @current_user.role.name == 'admin'
en unos de mis ticket se requeria verificar al Admin por el role_id , igual podemos hablar con el PM , porque de esa forma me parece que es valido tambien.

2022-03-04 18:38 UTC, chocolatito requested changes
Los archivos referidos al modulo de autenticación y autorización se pueden sacar

2022-03-04 18:38 UTC, chocolatito commented on app/controllers/api/v1/categories_controller.rb
> +      before_action :admin?, only: %i[update]
Por lo comentado en la ultima Daily, estas lineas se pueden borrar

2022-03-04 18:38 UTC, chocolatito commented on app/controllers/api/v1/categories_controller.rb
> +        @category = Category.find(params[:id])
En otros PR nos recomiendan usar los métodos terminados en ! para levantar la excepción.
En este caso, le corresponde una excepción del tipo `ActiveRecord::RecordNotFound`
```
@category = Category.find!(params[:id])
```

2022-03-04 19:40 UTC, chocolatito requested changes
Prueba realizada, el único cambio que falta es reemplazar el metodo `find!(<id>)` por `find_by!(id: <id>)` y agregar el archivo seriaializer

2022-03-04 19:40 UTC, chocolatito commented on app/controllers/api/v1/categories_controller.rb
> +        @category = Category.find!(params[:id])
Me equivoque en la anterior petición. El metodo correcto es
```
@category = Category.find_by!(id: params[:id])
```

2022-03-04 19:40 UTC, chocolatito commented on app/controllers/api/v1/categories_controller.rb
> +          render json: @category, status: :ok
Falta el serializer

2022-03-05 16:42 UTC, chocolatito submitted a review, later dismissed
Aprobado.

2022-03-06 00:13 UTC, FernandoCiballero approved these changes

2022-03-06 00:14 UTC, merged