Add soft-delete to users by id
alkemyTech/OT151-SERVER pull request #30
Opened 2022-03-02 19:31 UTC by MatiasDevJam

Soft-delete funcional.

2022-03-03 12:55 UTC, chocolatito requested changes
Podrías integrar la implementación del [PR#20: feat/OT151-31: add middleware for ownership](https://github.com/alkemyTech/OT151-SERVER/pull/20/files#diff-8810aba8895a54bf0634558929a55c68b3012b2973ff0300dd5d140272bd55fd)

2022-03-03 18:05 UTC, lautarograc commented on app/controllers/api/v1/users_controller.rb
> +        @user = User.find(params[:id]).discard
Según vi en la user story del ticket, se requiere que un usuario pueda eliminar su perfil, y acá se está permitiendo eliminar por ID y sin validar roles. ¿No podría ser mejor usar un current_user?

2022-03-03 19:53 UTC, Tinix commented on app/controllers/api/v1/users_controller.rb
> +        @user = User.find(params[:id]).discard
si tambien me pregunte lo mismo , y en el ticket dice lo siguiente: Criterios de aceptación:
DELETE a /users/:id Deberá recibir el id del usuario con el método DELETE. El borrado debe ser lógico. 
esta buena la pregunta del role , pero este ticket no lo requiere en todo caso lo hablamos con Fernando

2022-03-03 19:55 UTC, Tinix commented on app/controllers/api/v1/users_controller.rb
> +        render json: { message: 'User deleted' }
me parace que esta bien, igual me sumo al comentario de chocolatito de agregar es status

2022-03-07 02:00 UTC, chocolatito requested changes

2022-03-09 02:16 UTC, MatiasDevJam commented
Cierro PR. El ticket se resuelve en el siguiente [PR 45](https://github.com/alkemyTech/OT151-SERVER/pull/45)

2022-03-09 02:16 UTC, closed without merging