Ot151 41 endpoint eliminacion categorias
alkemyTech/OT151-SERVER pull request #31
Opened 2022-03-02 19:55 UTC by Tinix

COMO usuario administrador
QUIERO eliminar una categoría existente
PARA mantener la información actualizada

Criterios de aceptación:
DELETE /categories/:id - Deberá validar que la categoría existe y eliminarla, caso contrario devolver un error

2022-03-02 21:49 UTC, lautarograc requested changes
Hola Daniel, unos comentarios:
Estás añadiendo tus commits de todo el sprint en lugar de hacer una PR solo para el ticket 31, se hace un poco dificil visualizar los cambios apropiados.
Respecto al ticket, te deje un comentario acerca del controlador.
 Cuídate!

2022-03-02 21:49 UTC, lautarograc commented on app/controllers/api/v1/categories_controller.rb
> +          @category.destroy
Acá deberías usar discard para hacer un soft delete en lugar de destroy.

2022-03-03 00:56 UTC, chocolatito requested changes

2022-03-03 13:05 UTC, chocolatito requested changes

2022-03-03 13:05 UTC, chocolatito commented on app/controllers/concerns/authorized.rb
> +  end
Estas 3 funciones corresponden al middleware ownership del [PR#20](https://github.com/alkemyTech/OT151-SERVER/pull/20/files#diff-df86f18332cefbf90a3a451b40a416d927a63732a7a33297a427c1bb99e4ac52)
En toco caso, la función que debería modificarse seria
```
def admin
  render json: { errors: 'Unauthorized access' }, status: :forbidden unless admin?
end
```

2022-03-03 13:05 UTC, chocolatito commented on config/routes.rb
> +      get '/*a', to: 'application#not_found'
No queda claro el propósito de agregar un nuevo endpoint, en lugar de eso se deberían manejar las excepciones.

2022-03-03 20:02 UTC, Tinix commented on app/controllers/api/v1/categories_controller.rb
> +          @category.destroy
si eso habra que cambiarlo , gracias Lautaro!

2022-03-03 20:03 UTC, Tinix commented on app/controllers/api/v1/categories_controller.rb
> +          @category.destroy
estamos de acuerdo Daniel Ivan , gracias!

2022-03-03 20:04 UTC, Tinix commented on config/routes.rb
> +      get '/*a', to: 'application#not_found'
si, la linea 9 deberia removerla...

2022-03-06 00:30 UTC, merged