feat OT-151-38: add endpoint detail for category by id
alkemyTech/OT151-SERVER pull request #36
Opened 2022-03-07 00:15 UTC by MatiasDevJam

2022-03-07 02:12 UTC, chocolatito requested changes

2022-03-07 02:12 UTC, chocolatito commented on app/controllers/api/v1/categories_controller.rb
>        before_action :admin?, only: %i[update]
Esta linea no correspondería porque es funcionalidad de otro ticket..
Tampoco corresponderían los concerns `authenticable.rb` y `authorized.rb`.
En el caso de `exception_handler.rb` si podría conservarse, ya que ese archivo lo comparten los demás tickets tal cual esta.

2022-03-07 02:12 UTC, chocolatito commented on app/controllers/api/v1/categories_controller.rb
> +        render json: { error: "Category not found '#{params[:id]}'" }, status: :not_found
Si conservas el `exception_handler.rb`, deberías borrar estas lineas. Ya que siempre se levanta la excepción del concerns

2022-03-07 20:26 UTC, chocolatito commented on app/controllers/api/v1/categories_controller.rb
>        before_action :admin?, only: %i[update]
Bien.. lo acabo de ver.

2022-03-07 20:26 UTC, chocolatito approved these changes
Aprobado

2022-03-09 02:30 UTC, MatiasDevJam commented
Cierro PR. El ticket se resuelve en el siguiente [PR 46](https://github.com/alkemyTech/OT151-SERVER/pull/46)

2022-03-09 02:32 UTC, MatiasDevJam commented
Cierro PR. El ticket se resuelve en el siguiente [PR 46](https://github.com/alkemyTech/OT151-SERVER/pull/46)

2022-03-09 02:32 UTC, closed without merging