feat OT-151-42: add endpoint detail for announcement by id
alkemyTech/OT151-SERVER pull request #37
Opened 2022-03-07 01:36 UTC by MatiasDevJam

2022-03-07 02:15 UTC, chocolatito requested changes

2022-03-07 02:15 UTC, chocolatito commented on app/controllers/api/v1/announcements_controller.rb
> +        render json: { error: "Announcement not found '#{params[:id]}'" }, status: :not_found
Estas lineas estarían de mas ya que dispones de un manejador de excepciones [exception_handler.rb](https://github.com/alkemyTech/OT151-SERVER/blob/feat/OT-151-42-add-endpoint-detail-announcement/app/controllers/concerns/exception_handler.rb)

2022-03-07 02:18 UTC, chocolatito requested changes

2022-03-07 02:18 UTC, chocolatito commented on app/serializers/announcement_serializer.rb
> +  attributes :name, :content
Falta un atributo.
```
attributes :name, :content, :category_id
```

2022-03-08 01:54 UTC, FernandoCiballero commented on app/serializers/announcement_serializer.rb
> +  attributes :name, :content
En este caso el serializer tiene un método `belongs_to` para traer los registros asociados. [documentacions jsonapi-serializer](https://github.com/jsonapi-serializer/jsonapi-serializer#serializer-definition)

2022-03-08 01:55 UTC, FernandoCiballero requested changes
Dejo un comentario para revisar.

2022-03-09 03:16 UTC, MatiasDevJam commented
Cierro PR. El ticket se resuelve en el siguiente [PR 47](https://github.com/alkemyTech/OT151-SERVER/pull/47)

2022-03-09 03:16 UTC, closed without merging