Added feature to return a token when a new user registers
alkemyTech/OT151-SERVER pull request #42
Opened 2022-03-08 20:13 UTC by lautarograc

Según el [ticket 46](https://alkemy-labs.atlassian.net/browse/OT151-46?atlOrigin=eyJpIjoiMWE5MTllMmE4YTAzNDlmYjk2YzMxMjI2YWRlNzVlMDUiLCJwIjoiaiJ9), ahora al registrarse un nuevo usuario se devuelve un token para autorizar futuras requests.

También se arregló una typo en las rutas, se eliminó la constraint "authorize_request" que no existe como método y se agregó una validación para que solo los dueños de un usuario puedan editar su información (caso contrario, el token de, por ejemplo, el usuario id=>25 puede editar la información del usuario id=>34).

2022-03-08 21:43 UTC, chocolatito requested changes

2022-03-08 21:43 UTC, chocolatito commented on app/controllers/api/v1/users_controller.rb
> +          render json: { serialize_user: serialize_user, token: token }, status: :created
Se puede serializar el el token como una clave objeto meta:
```
options = {}
options[:meta] = {  token: JsonWebToken.encode(user_id: @user.id) }
UserSerializer.new(@user, options).serializable_hash.to_json
```

Consultar:
- https://github.com/jsonapi-serializer/jsonapi-serializer#meta-per-resource
- https://github.com/jsonapi-serializer/jsonapi-serializer#compound-document

2022-03-08 22:19 UTC, chocolatito requested changes

2022-03-08 22:19 UTC, chocolatito commented on app/controllers/api/v1/users_controller.rb
>          @user.role = Role.create_or_find_by(name: 'user', description: 'usuario de la aplicacion')
mejor usar el metodo `find_or_create_by!` ya que la columna `name` no posee restricción de unicidad. Para levantar la excepción se usa la exclamación al final.
```
 @user.role = Role.find_or_create_by!(name: 'user', description: 'usuario de la aplicacion')
 ```

2022-03-08 22:19 UTC, chocolatito commented on app/controllers/api/v1/users_controller.rb
>          if @user.save
Para levantar la excepción se usa la exclamación al final.
Puedes tomar como referencia archivo de este [PR](https://github.com/alkemyTech/OT151-SERVER/pull/34/files#diff-ef20d40ddd2dd2a254d26fd4c59655cbed6b541c5f908b81125d09848c1dfeb6)

2022-03-09 20:02 UTC, lautarograc commented on app/controllers/api/v1/users_controller.rb
> +          render json: { serialize_user: serialize_user, token: token }, status: :created
No entiendo por qué se debería serializar el token, ya que en realidad la [gema de JWT](https://github.com/jwt/ruby-jwt) se encarga de serializar el header, el payload y la firma al momento de cifrar el token, además de que el token no es un atributo del usuario que se debe devolver en la response.

2022-03-09 20:40 UTC, chocolatito commented on app/controllers/api/v1/users_controller.rb
> +          render json: { serialize_user: serialize_user, token: token }, status: :created
> No entiendo por qué se debería serializar el token, ya que en realidad la [gema de JWT](https://github.com/jwt/ruby-jwt) se encarga de serializar..

La gema responsable de serializar es [jsonapi-serializer](https://github.com/jsonapi-serializer/jsonapi-serializer), independientemente de si usas JSonWedToken o algún otro estándar de autenticación, esta gema simplemente es una abstracción para que al usarla, les das los datos y la gema se encarga de devolver el formato de salida según la especificación [JSON:API](https://jsonapi.org/) (que es lo que usamos para RESTful), en lugar de que nosotros nos pongamos a codificar toda la salida.

La gema JWT es la implementación del estándar [RFC 7519 OAuth JSON Web Token (JWT)](https://tools.ietf.org/html/rfc7519), que en resumen, es una convención sobre mecanismos para autenticación basado en cifrado de objetos JSON.

> ...además de que el token no es un atributo del usuario que se debe devolver en la response.

Ese es el propósito de estas referencias
- [meta-per-resource](https://github.com/jsonapi-serializer/jsonapi-serializer#meta-per-resource)
- [compound-document](https://github.com/jsonapi-serializer/jsonapi-serializer#compound-document)

La idea, según tengo entendido, es que al usar el formato [JSON:API](https://jsonapi.org/), quien sea que consuma nuestra api y todas las que sigan el mismo formato, sepa que en que parte del JSON tiene que buscar información de los atributos del modelo y en donde buscar el token (que no es un atributo).

2022-03-09 20:48 UTC, lautarograc commented on app/controllers/api/v1/users_controller.rb
> +          render json: { serialize_user: serialize_user, token: token }, status: :created
Es que justamente para mi no se debería entregar el token en el JSON de los params del usuario. El JWT sería usado para autorizar requests desde afuera hacia nuestra API y no consumido por aplicaciones de terceros. El token no guarda relación con el modelo de usuario.

2022-03-09 20:49 UTC, lautarograc commented
Realicé algunos cambios menores en el controlador en base a sugerencias. Siguen en discusión otros puntos del review.

2022-03-09 20:49 UTC, chocolatito commented on app/controllers/api/v1/users_controller.rb
> +          render json: { serialize_user: serialize_user, token: token }, status: :created
Otra ejemplo de serializar datos que no son del modelo es cuando usamos paginación.
En el [Cap 9](https://github.com/madeindjs/api_on_rails/blob/master/rails6/en/chapter09-optimization.adoc) del libro que nos dan de referencia en el proyecto, propone lo siguiente:
```
class Api::V1::ProductsController < ApplicationController
  include Paginable
  # ...
  def index
    @products = Product.page(current_page)
                       .per(per_page)
                       .search(params)

    options = {
      links: {
        first: api_v1_products_path(page: 1),
        last: api_v1_products_path(page: @products.total_pages),
        prev: api_v1_products_path(page: @products.prev_page),
        next: api_v1_products_path(page: @products.next_page),
      }
    }

    render json: ProductSerializer.new(@products, options).serializable_hash.to_json
  end
end
```

En ese ejemplo, `links` no es un atributo del modelo `Product`, no obstante, seria una violación al formato de salida utilizado en el proyecto si no se incluye en el serializer.

2022-03-13 23:02 UTC, FernandoCiballero approved these changes
Muy Bien Lautaro!!! corregí un typo, estaba mal escrito el método `find_or_create_by!`. De todos modos estaría podría recomendarme estar atento a los cambios solicitados ya que Ivan te comentó unas modificaciones y vi que no estaba aplicados esos cambios.

2022-03-13 23:02 UTC, merged