feat OT-151-38: add endpoint detail category
alkemyTech/OT151-SERVER pull request #46
Opened 2022-03-09 02:29 UTC by MatiasDevJam

Corrección del PR anterior para evitar varios conflictos de commits.

2022-03-09 03:23 UTC, MatiasDevJam commented on app/controllers/api/v1/categories_controller.rb
>        before_action :admin?, only: %i[update]
Revisar: Este endpoint esta restringido a solo usuario administrador.
Debo implementar el callback admin?
Ejemplo:
**_before_action :admin, only: %i[show update]_**

2022-03-09 13:41 UTC, chocolatito requested changes

2022-03-09 13:41 UTC, chocolatito commented on app/controllers/api/v1/categories_controller.rb
>        before_action :admin?, only: %i[update]
En efecto, el método `admin?` solo retorna `true` o `false` pero no retorna una excepción en caso de no cumplir la autorización. Se debe corregir esa linea por `admin`

2022-03-09 14:29 UTC, chocolatito approved these changes
Aprobado.

2022-03-13 20:45 UTC, lautarograc approved these changes

2022-03-13 23:24 UTC, FernandoCiballero approved these changes
Muy bien Matias!!! 👍

2022-03-13 23:25 UTC, merged