feat OT-151-42: add endpoint detail announcement
alkemyTech/OT151-SERVER pull request #47
Opened 2022-03-09 03:15 UTC by MatiasDevJam

Correcion del PR anterior para evitar varios conflictos de commits.

2022-03-09 03:22 UTC, MatiasDevJam commented on app/controllers/api/v1/announcements_controller.rb
>      class AnnouncementsController < ApplicationController
Revisar: Este endpoint esta restringido a solo usuario administrador.
Debo implementar el callback admin?
Ejemplo:
**_before_action :admin, only: %i[show]_**

2022-03-09 03:24 UTC, MatiasDevJam commented on app/serializers/announcement_serializer.rb
> +  belongs_to :category
Revisar si esto es correcto, por favor.

2022-03-09 13:38 UTC, chocolatito requested changes
Solo cambios sencillos

2022-03-09 13:38 UTC, chocolatito commented on app/controllers/api/v1/announcements_controller.rb
>      class AnnouncementsController < ApplicationController
En efecto esta faltando esa linea, aun cuando no existe la implementación

2022-03-09 13:38 UTC, chocolatito commented on app/serializers/announcement_serializer.rb
> +  belongs_to :category
Es correcto

2022-03-09 13:38 UTC, chocolatito commented on config/routes.rb
> +      resources :announcements, only: %i[show]
Respetar orden alfabético
```
   # [...]
      resources :announcements, only: %i[show]
      post 'auth/register', to: 'users#create'
      post 'auth/login', to: 'auth#create'
   # [...]
```

2022-03-09 14:14 UTC, MatiasDevJam commented on app/controllers/api/v1/announcements_controller.rb
>      class AnnouncementsController < ApplicationController
Resuelto.

2022-03-09 14:27 UTC, chocolatito approved these changes
Todo en orden. Aprobado

2022-03-13 20:49 UTC, lautarograc requested changes

2022-03-13 20:49 UTC, lautarograc commented on config/routes.rb
> +      resources :announcements, only: %i[show]
La ruta no está cumpliendo con el [ticket](https://alkemy-labs.atlassian.net/browse/OT151-42?atlOrigin=eyJpIjoiYTI1NzIwNTM4YTViNGQ3OGE2NDQ2YjQ3NGIxNzE3YmYiLCJwIjoiaiJ9). Fíjate de agregar un path tal que
`resources :adnnouncements, only: %i[show], **path: '/news'**

2022-03-13 23:28 UTC, FernandoCiballero commented on config/routes.rb
> +      resources :announcements, only: %i[show]
En este caso, dado que cambiamos el nombre del modelo a `announcements`, es valido usar la ruta `/announcements`

2022-03-13 23:29 UTC, FernandoCiballero submitted a review, later dismissed
Bien Matias Aprobado!!!

2022-03-13 23:42 UTC, merged