feat OT-151-51: add endpoint create testimonial
alkemyTech/OT151-SERVER pull request #48
Opened 2022-03-09 15:33 UTC by MatiasDevJam

COMO usuario administrador
QUIERO dar de alta nuevos Testimonios
PARA informar Novedades acerca de la ONG.

Criterios de aceptación:
POST /testimonials - Deberá validar la existencia de los campos name y content enviados, para almacenar el registro en la tabla testimonials.

Detalles a tener en cuenta:
Endpoint implmentado utilizando el [exception_handler.rb](https://github.com/alkemyTech/OT151-SERVER/blob/main/app/controllers/concerns/exception_handler.rb)

2022-03-09 15:40 UTC, chocolatito requested changes
Falta agregar una sola linea

2022-03-09 15:40 UTC, chocolatito commented on app/controllers/api/v1/testimonials_controller.rb
> +      before_action :admin, only: %i[create]
Antes de la linea 6, siempre se debe autenticar la solicitud basada en el token enviado en el request
```
      before_action :authenticate_with_token!, only: %i[create]
      before_action :admin, only: %i[create]
```

2022-03-09 16:00 UTC, MatiasDevJam commented on app/controllers/api/v1/testimonials_controller.rb
> +      before_action :admin, only: %i[create]
Cambio realizado.

2022-03-09 16:05 UTC, chocolatito submitted a review, later dismissed
Listo para merge

2022-03-13 20:53 UTC, lautarograc submitted a review, later dismissed

2022-03-13 23:44 UTC, FernandoCiballero submitted a review, later dismissed
Muy bien Matias!!! 👍

2022-03-13 23:45 UTC, merged