feat OT-151-54: Setup Kaminari and add pagination to testimonial
alkemyTech/OT151-SERVER pull request #50
Opened 2022-03-09 22:32 UTC by MatiasDevJam

Agregada la gema Kaminari. 
El modulo Paginable se puede reutilizar para paginacion en otros modelos.

2022-03-10 13:55 UTC, chocolatito requested changes
bastante bien

2022-03-10 13:55 UTC, chocolatito commented on app/controllers/api/v1/testimonials_controller.rb
> +      end
Recomendaría el siguiente cambio:
```
    def index
      # [...]
      render json: serialize_testimonial(@testimonials, @options), status: :ok
    end

    def create
      @testimonial = Testimonial.create!(testimonial_params)
      render json: serialize_testimonial(@testimonial), status: :created
   end

    # [...]
    def serialize_testimonial(*args)
      TestimonialSerializer.new(*args).serializable_hash.to_json
    end
    # [...]   
```

2022-03-10 17:35 UTC, MatiasDevJam commented on app/controllers/api/v1/testimonials_controller.rb
> +      end
Refactor del método **serialize_testimonial** realizado.
Agregado el método **kept** de Discard al método index para ocultar los registros eliminados con soft-delete.

2022-03-10 19:16 UTC, chocolatito approved these changes
Aprobado.

> Comentario aparte:
> - Cuando actualizar tus PRs, tienes que presionar las dos flechas que se apuntan para avisarle (al que te realizo una petición de cambio) que requiere una nueva revisión (Re-request review).
>> - Cuando realizas las revisiones de PR de tus compañeros, y tocas las flechas de tu revision, se cancela y tienes que volver a revisar de nuevo. Es igual cuando apruebas cambios de tus compañeros y tocas la fecha de tu usuario, cancelas tu aprobación. 

![Captura de pantalla de 2022-03-10 16-08-45](https://user-images.githubusercontent.com/42852456/157737096-3bbfced0-cd95-4f65-9fa5-fe0d86bd968a.png)

2022-03-13 21:00 UTC, lautarograc submitted a review, later dismissed
Bien. Buena implementación de kaminari.

2022-03-14 00:01 UTC, FernandoCiballero approved these changes
Muy bien Matias!!! 🚀

2022-03-14 00:01 UTC, merged