feat OT-151-43: add endpoint create announcement
alkemyTech/OT151-SERVER pull request #51
Opened 2022-03-10 03:16 UTC by MatiasDevJam

COMO usuario administrador
QUIERO agregar una novedad en el sistema
PARA poder informar las Novedades de la ONG

Criterios de aceptación:
POST /news - Deberá validar la existencia de los campos enviados, para almacenar el registro en la tabla news. Antes de almacenarla, deberá asignarle la columna type con el valor "news".

Modificaciones:
Se agregaron las modificaciones de la tabla Annoucement a los archivos de test.
- **announcements.rb**
- **announcement_spec.rb**

2022-03-10 03:18 UTC, MatiasDevJam commented on app/controllers/api/v1/announcements_controller.rb
> +        @announcement.category = Category.create_or_find_by(name: 'news',
Revisar si esto es correcto, si cumple los requerimientos del ticket.

2022-03-10 14:29 UTC, chocolatito requested changes

2022-03-10 14:29 UTC, chocolatito commented on app/controllers/api/v1/announcements_controller.rb
> +        @announcement.category = Category.create_or_find_by(name: 'news',
Me parece esta linea no corresponde y que el método `announcement_params` admite el valor para `category_id `. Por lo tanto al ejecutar la linea 9, ya existe el enlace a la categoría.

2022-03-10 14:29 UTC, chocolatito commented on app/controllers/api/v1/announcements_controller.rb
> +        end
Siguiendo el patrón de código que venimos manejando en otros controladores, sugiero el siguiente cambio:

```
  def create
    # [...]
    @announcement.save!
    render json: announcement_serializer, status: :created
  end
  # [...]
```

2022-03-10 14:29 UTC, chocolatito commented on app/controllers/api/v1/announcements_controller.rb
> +      end
Podrías implementar la lógica sugerida en el archivo e este [PR](https://github.com/alkemyTech/OT151-SERVER/pull/50/files#diff-9e3cbf8cf4db463a6f7626854614855b96fb341832a35b06021942e42f3ffa6a) de manera que si en el futuro se añade la acción `index` con paginación, se pueda reutilizar este método

2022-03-11 13:24 UTC, MatiasDevJam commented on app/controllers/api/v1/announcements_controller.rb
> +        @announcement.category = Category.create_or_find_by(name: 'news',
Sin esas lineas, tengo errores de validación.

2022-03-13 21:06 UTC, lautarograc commented on config/routes.rb
> +      post 'news', to: "announcements#create"
Acá podrías integrarlo en un resources como hiciste en el [ticket 42](https://github.com/alkemyTech/OT151-SERVER/pull/47), para ahorrarnos un poco de código.

2022-03-13 21:09 UTC, lautarograc commented on app/controllers/api/v1/announcements_controller.rb
> +        @announcement.category = Category.create_or_find_by(name: 'news',
Tampoco entiendo la presencia de la línea 11. Me parece que el error te lo está devolviendo algo ajeno al ticket. Cuando eliminas la línea e intentás crear una novedad, al asignarle un id de categoría, ¿esa categoría existe en la base de datos? Es probable que te este fallando esa validación.

2022-03-14 01:28 UTC, merged