feat OT-151-57: Setup Rswag gem and adds documentation to testimonials
alkemyTech/OT151-SERVER pull request #58
Opened 2022-03-15 23:55 UTC by MatiasDevJam

Configuración de Rswag siguiendo el  [Turorial](https://github.com/chocolatito/SETUP-RSWAG) de @chocolatito.

Documentación de Tesimonials de prueba funcionando.

2022-03-18 00:50 UTC, FernandoCiballero approved these changes
Genial el Laburo Matías!!!

2022-03-18 14:57 UTC, chocolatito requested changes
Podrías seguir la siguiente organización de los test como recomendó en [este comentario](https://github.com/alkemyTech/OT151-SERVER/pull/60#pullrequestreview-913844302)
```
spec/integration/api/v1/testimonials/
spec/integration/api/v1/testimonials/create_spec.rb
```

2022-03-18 14:57 UTC, chocolatito commented on app/controllers/api/v1/testimonials_controller.rb
> +      # before_action :admin, only: %i[create]
El ticket [OT151-51](https://alkemy-labs.atlassian.net/browse/OT151-51) especifica que solo el administrador esta autorizado para la acción `create`

2022-03-18 14:57 UTC, chocolatito commented on spec/swagger_helper.rb
> +      ]
Puedes guiarte de la configuración del [PR#62](https://github.com/alkemyTech/OT151-SERVER/pull/62) para lograr la autorización
```
definitions: {
        # ...
        securityDefinitions: { .. }
}
```

2022-03-18 14:57 UTC, chocolatito commented on spec/integration/api/v1/testimonials_spec.rb
> +      tags tags_testimonial
Las constantes siempre van todo con mayúscula, tienes dos alternativas.
- Reemplazar la linea 6 por `TAGS_TESTIMONIAL = 'Testimonials'`
- La otra alternativa es eliminar la linea 6 y reemplazar la 10 por `:Testimonials`

2022-03-21 00:27 UTC, MatiasDevJam commented
Cierro PR, lo finaliza @chocolatito

2022-03-21 00:27 UTC, closed without merging