Added model, migration and base controller for User
alkemyTech/OT151-SERVER pull request #6
Opened 2022-02-19 03:46 UTC by lautarograc

Agregué las validaciones del modelo, expandí los tests y adequé los atributos a las convenciones.
Eliminé el placeholder de roles en la base de datos. 
Los tests cubren el 60% del código y todas las validaciones con posibles casos de error para el usuario.

2022-02-20 16:32 UTC, FernandoCiballero commented on app/controllers/api/v1/users_controller.rb
> +end
Verificar la indentacion 🙏 porfa.

2022-02-20 16:33 UTC, FernandoCiballero commented on spec/factories/users.rb
> +    email { 'example@email.com' }
Podrías implementar Faker para generar los datos en este caso.

2022-02-20 16:36 UTC, FernandoCiballero commented on app/models/user.rb
> +
Este espacio entre los `validates` se prodría eliminar.

2022-02-20 16:38 UTC, lautarograc commented on app/controllers/api/v1/users_controller.rb
> +end
> 

Buenas. La identación la cambié debido a lo que se había [comentado en mi PR anterior](https://github.com/alkemyTech/OT151-SERVER/pull/3#discussion_r810328518) donde se señaló que una identación de 6 espacios  para la clase podía ser molesto. Supongo que después lo hablaremos en la daily.

2022-02-20 16:39 UTC, FernandoCiballero commented on .rubocop_todo.yml
> +# This configuration was generated by
Cuál fue tú idea a la hora de incuir el .rubocop_todo.yml? tal vez se podria omitir por ahora hasta tanto surja la necesidad de usarlo.

2022-02-20 16:42 UTC, FernandoCiballero commented on spec/models/user_spec.rb
> +  # testing discard gem
Buenisimo el laburo!!!, aunque hay examples que corresponden a un test de `requests` valoro el esfuerzo. Ahora el desafío es reducir un poco el código usando shoulda matchers:
https://github.com/thoughtbot/shoulda-matchers#usage

2022-02-20 16:43 UTC, FernandoCiballero requested changes
Buen Laburo!!! 👍 te dejo unos comentarios.

2022-02-20 16:45 UTC, chocolatito commented on app/controllers/api/v1/users_controller.rb
> +end
@lautarograc, en el PR que hice antes de hacerte el comentario, no me habían hecho esa observación, así que no pense que era relevante, pero justamente hoy me aclararon el tema del _Style/ClassAndModuleChildren_, asi que lo mejor es que lo respetemos.

2022-02-20 19:03 UTC, lautarograc reviewed
En base a los comentarios, los tests ahora estan estructurados con Shoulda Matchers, eliminé el rubocop todo, arreglé la identación, la factory ahora utiliza Faker y le agregué un índice a la unicidad de los emails en base a las [respuestas de esta pregunta de stackoverflow](https://stackoverflow.com/questions/69323472/rubocop-uniqueness-validation-should-be-with-a-unique-index-in-values-that-star)

2022-02-21 04:11 UTC, FernandoCiballero commented on Gemfile
> +gem 'discard', '~> 1.2', '>= 1.2.1'
Genial!!! un detalle para que quede prolijo, le podrias agregar el link de rubygems al costado como tienen las otras gemas.

2022-02-21 04:15 UTC, FernandoCiballero commented on spec/models/user_spec.rb
> +  end
Revisa el uso de `describe` y `context` en rspec. En slack te pase el formato.

2022-02-21 04:18 UTC, FernandoCiballero commented on app/controllers/api/v1/users_controller.rb
> +end
Genial!!! 👍

2022-02-21 04:18 UTC, FernandoCiballero requested changes
Buenisimo!!! te deje un par de comentarios.

2022-02-22 05:10 UTC, lautarograc commented
Cierro este PR para iniciar uno nuevo desde la repo del proyecto en vez desde mi fork.

2022-02-22 05:10 UTC, closed without merging