Test/ot 151 61 test endpoints news
alkemyTech/OT151-SERVER pull request #63
Opened 2022-03-17 21:29 UTC by lautarograc

en progreso

2022-03-17 22:18 UTC, chocolatito requested changes
En el orden que va, le vas a poder entender la idea.

2022-03-17 22:18 UTC, chocolatito commented on app/controllers/api/v1/announcements_controller.rb
>        def create
1ro) Cuando ejecuto el debug en esta acción, el test no le esta enviando el valor de `category_id`.
El controlador esta recibiendo esto
```
#<ActionController::Parameters {"announcement"=>{"name"=>"Jimmy McGill", "content"=>"Tenebrous accursed unnamable fainted ululate.", "type"=>"rem"}, "format"=>"json", "controller"=>"api/v1/announcements", "action"=>"create"} permitted: false>
```

2022-03-17 22:18 UTC, chocolatito commented on app/controllers/api/v1/announcements_controller.rb
>          @announcement = Announcement.new(announcement_params)
2do) Al ejecutar esta linea, el valor de ` @announcement` queda así:
```
#<Announcement:0x0000560073fa0798
 id: nil,
 name: "Jimmy McGill",
 content: "Tenebrous accursed unnamable fainted ululate.",
 created_at: nil,
 updated_at: nil,
 discarded_at: nil,
 category_id: nil,
 type: nil>
```
El controlador no esta recibiendo el valor de `category_id`

2022-03-17 22:18 UTC, chocolatito commented on spec/requests/api/v1/announcements/announcement_spec.rb
> +    attrs = attributes_for(:announcement)
3ro) El ejecutar esta linea, se genera la siguiente salida:
```
{:name=>"Adam Pinkman", :content=>"Effulgence unmentionable dank singular.", :type=>"earum"}
```
Esta faltando obtener el path de la imagen..

Lo que intente y funciono es lo siguiente:
```
attrs = attributes_for(:announcement).merge(
        image: Rails.root.join('spec/factories_files/test.png')
      )
```
Con esa misma idea, le podrías añadir un `category_id` que es lo que te esta faltando recibir en el controlador.
No es lo mas limpio, lo idal seria manejar todo desde el factory, pero puedes salir de paso con esto.

2022-03-18 00:59 UTC, FernandoCiballero commented on spec/rails_helper.rb
> +
Se podría pasar esto a un archivo en la carpeta `support` y despues requerirlo acá.

2022-03-18 01:00 UTC, FernandoCiballero reviewed
Te deje una pequeña modificación para hacer.

2022-03-18 01:23 UTC, lautarograc commented on app/controllers/api/v1/announcements_controller.rb
>        def create
¿Que debug ejecutas? por curiosidad

2022-03-18 03:03 UTC, chocolatito commented on app/controllers/api/v1/announcements_controller.rb
>        def create
En el proyecto tenemos disponible esta gema >> https://github.com/deivid-rodriguez/pry-byebug

2022-03-18 18:39 UTC, chocolatito requested changes
Lo prove con los cambios comentados y funcionaba.
Necesitas tener fusionado tu branch con la ultima actualización del main y correr la migración si hace falta.

---
Podrías seguir la siguiente organización de los test como recomendó en [este comentario](https://github.com/alkemyTech/OT151-SERVER/pull/60#pullrequestreview-913844302)
```
spec/requests/api/v1/announcements/show_spec.rb
spec/requests/api/v1/announcements/create_spec.rb
spec/requests/api/v1/announcements/update_spec.rb
```

>NOTA: Al hacer esto, se debe eliminar el archivo `spec/requests/api/v1/announcements_spec.rb`.

2022-03-18 18:39 UTC, chocolatito commented on spec/factories/announcements.rb
>      type { Faker::Lorem.word }
Despues de haber corrido la migración modifica el nombre de la columna `type` por `announcements_type `, reemplazar
```
# spec/factories/announcements.rb
  announcements_type { Faker::Lorem.word }
```

```
# app/models/announcement.rb
  validates :announcement_type, presence: true, length: { minimum: 2 }
```

```
# app/serializers/announcement_serializer.rb
  attributes :name, :content, :announcement_type
```

2022-03-18 18:39 UTC, chocolatito commented on app/controllers/api/v1/announcements_controller.rb
>          @announcement.type = 'news'
Despues de haber corrido la migración modifica el nombre de la columna `type` por `announcements_type`, reemplazar esta linea por `@announcement.announcement_type = 'news'`

2022-03-18 18:48 UTC, chocolatito requested changes
esta imagen (spec/fixture/files/Rosario.jpg) no debería ser subida.
Si no usas las imágenes del `spec/factories_files`, de deberías colocar las imágenes en la carpeta `./temp` para que sean ignoradas al momento de hacer push

2022-03-19 18:12 UTC, closed without merging