Added documentation for members
alkemyTech/OT151-SERVER pull request #66
Opened 2022-03-18 18:24 UTC by lautarograc

Agregada la documentación para miembros.
Se utiliza la integración con RSPEC de Swagger ([rswag](https://rubygems.org/gems/rswag)). 
Todos los tests de integración pasan.

Para comprobar la documentación, correr el comando:
`rails rswag
Luego, navegar a [http://localhost:3000/api-docs/index.html](http://localhost:3000/api-docs/index.html)

2022-03-18 19:22 UTC, chocolatito requested changes
No me genera los datos, por lo que realice las siguientes modificaciones comentadas.

---
Ademas de lo comentado, falta la siguiente configuración:
```
# /config/application.rb
# [...]
module OT151Server
  class Application < Rails::Application
    # [...]
    config.api_only = true
    if Rails.env.test?
      RSpec.configure do |config|
        config.swagger_dry_run = false
      end
    end
  end
end
```

---
Podrías seguir la siguiente organización de los test como recomendó en [este comentario](https://github.com/alkemyTech/OT151-SERVER/pull/60#pullrequestreview-913844302)
```
spec/integration/api/v1/members/index_spec.rb
```

>NOTA: Al hacer esto, se debe eliminar el archivo `spec/integration/api/v1/members_spec.rb`.

2022-03-18 19:22 UTC, chocolatito commented on spec/integration/api/v1/members_spec.rb
> +                run_test!
Despues de esta linea debería ir
```
        after do |example|
          example.metadata[:response][:examples] =
            { 'application/json' => JSON.parse(response.body, symbolize_names: true) }
        end

2022-03-18 19:22 UTC, chocolatito commented on spec/integration/api/v1/members_spec.rb
> +                let(:member) { create_list(:members, 10)}
Reemplazar por ` let(:member) { create_list(:member, 10)} `

2022-03-18 19:22 UTC, chocolatito commented on spec/swagger_helper.rb
> +      openapi: '3.0.1',
reemplazar por `swagger: '2.0',`

2022-03-18 22:52 UTC, lautarograc reviewed
Agregados algunos fixes

2022-03-19 02:26 UTC, chocolatito requested changes
No se debe pushear este archivo > `swagger/v1/swagger.yaml`  
Puedes hacer [este cambio](abfe519c5671395fd494d8cce506c42947) en el `.gitignore`

---
No parece tener algún error, pero no puedo generar los datos.
Levanta la pagina pero sigue sin mostrar el json serilizado, igual que en la demo.

2022-03-19 02:26 UTC, chocolatito commented on spec/integration/api/v1/members_spec.rb
> +                run_test!
esta linea esta de mas, `include_context 'with integration test'` ya ejecuta los tests.

2022-03-19 20:21 UTC, lautarograc commented
Expandido los tests para incluir la integración con los cambios realizados según el [ticket 47](https://alkemy-labs.atlassian.net/browse/OT151-47?atlOrigin=eyJpIjoiNTlkNGZlNTBkZTJmNGIxZTllZTYwYzBlZjY3NDM1NDAiLCJwIjoiaiJ9) en el PR [71](https://github.com/alkemyTech/OT151-SERVER/pull/71).

2022-03-20 22:14 UTC, chocolatito requested changes
Los test de integración falla, por lo que la documentación que se genera no muestra los casos.
![doc-members](https://user-images.githubusercontent.com/42852456/159188275-b7c806b8-f5d2-49af-809b-1eebfd05ef16.png)

2022-03-21 02:10 UTC, merged